import sqlite3
import xml.etree.ElementTree as ET
from pathlib import Path
from dataclasses import dataclass, field

try:
    import defusedxml.ElementTree as _safe_ET
    _xml_parse = _safe_ET.parse
except ImportError:
    # defusedxml not installed; ET.parse with expat is acceptable for LOCAL
    # coverage files generated by the project's own test suite (trusted input).
    _xml_parse = ET.parse

@dataclass
class CoverageData:
    """In-memory coverage map. {absolute_path: set of covered line numbers}"""
    source: str  # "lcov" | "python" | "go" | "cobertura" | "none"
    covered_lines: dict[str, set[int]] = field(default_factory=dict)

    def is_covered(self, abs_path: str, line_start: int, line_end: int) -> bool:
        """True if ANY line in [line_start, line_end] appears in coverage data."""
        file_cov = self.covered_lines.get(abs_path, set())
        return any(ln in file_cov for ln in range(line_start, line_end + 1))

COVERAGE_SEARCH_PATHS = [
    ("lcov.info",             "lcov"),   # root-level canonical placement first
    ("coverage/lcov.info",    "lcov"),   # Jest/Istanbul default output second
    (".nyc_output/lcov.info", "lcov"),
    (".coverage",          "python"),
    ("coverage.out",       "go"),
    ("coverage/coverage.out", "go"),
    ("coverage.xml",       "cobertura"),
    ("coverage/coverage.xml", "cobertura"),
]

class CoverageReader:

    @classmethod
    def load(cls, project_root: Path) -> CoverageData:
        """
        Auto-detect and parse first coverage file found.
        Returns CoverageData(source='none') if nothing found — never raises.
        """
        for relative, fmt in COVERAGE_SEARCH_PATHS:
            path = project_root / relative
            if not path.exists():
                continue
            try:
                if fmt == "lcov":
                    return cls._parse_lcov(path, project_root)
                elif fmt == "python":
                    return cls._parse_python_coverage(path, project_root)
                elif fmt == "go":
                    return cls._parse_go_coverage(path, project_root)
                elif fmt == "cobertura":
                    return cls._parse_cobertura(path, project_root)
            except (ValueError, KeyError, IndexError,
                    sqlite3.DatabaseError, ET.ParseError):
                continue
            except (OSError, PermissionError) as e:
                print(f"[codeindex] Warning: Cannot read coverage file {path}: {e}")
                continue
        return CoverageData(source="none")

    @classmethod
    def _parse_lcov(cls, path: Path, project_root: Path) -> CoverageData:
        covered: dict[str, set[int]] = {}
        current_file = None
        with path.open(encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if line.startswith("SF:"):
                    raw = line[3:]
                    p = Path(raw)
                    current_file = str(p if p.is_absolute() else (project_root / p))
                    covered.setdefault(current_file, set())
                elif line.startswith("DA:") and current_file is not None:
                    try:
                        parts = line[3:].split(",")
                        line_no = int(parts[0])
                        hits = int(parts[1])
                        if hits > 0:
                            covered[current_file].add(line_no)
                    except (ValueError, IndexError):
                        pass
                elif line == "end_of_record":
                    current_file = None
        return CoverageData(source="lcov", covered_lines=covered)

    @classmethod
    def _parse_python_coverage(cls, path: Path, project_root: Path) -> CoverageData:
        covered: dict[str, set[int]] = {}
        con = sqlite3.connect(str(path))
        try:
            try:
                files = {row[0]: row[1] for row in
                         con.execute("SELECT id, path FROM file")}
                for file_id, file_path in files.items():
                    abs_path = str(Path(file_path) if Path(file_path).is_absolute()
                                   else project_root / file_path)
                    lines = set()
                    for (numbits,) in con.execute(
                        "SELECT numbits FROM line_bits WHERE file_id=?", (file_id,)
                    ):
                        for byte_idx, byte_val in enumerate(numbits):
                            for bit in range(8):
                                if byte_val & (1 << bit):
                                    lines.add(byte_idx * 8 + bit + 1)
                    covered[abs_path] = lines
            except sqlite3.OperationalError:
                try:
                    # Fallback for coverage.py 5.x+ branch-coverage mode: the `arc`
                    # table records transitions between lines (fromno → tono).
                    # Schema: arc(file_id INTEGER, fromno INTEGER, tono INTEGER).
                    # Special values: 0 = function entry/exit; negative = exception arc.
                    # Both fromno > 0 and tono > 0 represent real source lines that were
                    # traversed, so both are added to the covered set.
                    files = {row[0]: row[1] for row in
                             con.execute("SELECT id, path FROM file")}
                    for file_id, file_path in files.items():
                        abs_path = str(Path(file_path) if Path(file_path).is_absolute()
                                       else project_root / file_path)
                        lines = set()
                        for (from_l, to_l) in con.execute(
                            "SELECT fromno, tono FROM arc WHERE file_id=?", (file_id,)
                        ):
                            if from_l > 0:
                                lines.add(from_l)
                            if to_l > 0:
                                lines.add(to_l)
                        covered[abs_path] = lines
                except sqlite3.OperationalError:
                    files = {row[0]: row[1] for row in
                             con.execute("SELECT id, path FROM file")}
                    for file_id, file_path in files.items():
                        abs_path = str(Path(file_path) if Path(file_path).is_absolute()
                                       else project_root / file_path)
                        lines = set()
                        for (line_no,) in con.execute(
                            "SELECT lineno FROM line_data WHERE file_id=?", (file_id,)
                        ):
                            if line_no > 0:
                                lines.add(line_no)
                        covered[abs_path] = lines
        finally:
            con.close()
        return CoverageData(source="python", covered_lines=covered)

    @classmethod
    def _parse_go_coverage(cls, path: Path, project_root: Path) -> CoverageData:
        covered: dict[str, set[int]] = {}
        with path.open(encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if line.startswith("mode:"):
                    continue
                parts = line.split(" ")
                if len(parts) != 3:
                    continue
                try:
                    hit_count = int(parts[2])
                    if hit_count == 0:
                        continue
                    location = parts[0]
                    colon_idx = location.rfind(":")
                    if colon_idx < 0:
                        continue
                    file_part = location[:colon_idx]
                    range_part = location[colon_idx + 1:]
                    start_str, end_str = range_part.split(",")
                    start_line = int(start_str.split(".")[0])
                    end_line = int(end_str.split(".")[0])
                    file_parts = Path(file_part).parts
                    matched_candidate = None
                    for n in range(len(file_parts), 0, -1):
                        suffix = Path(*file_parts[-n:])
                        candidate = project_root / suffix
                        if candidate.exists():
                            matched_candidate = candidate
                            break
                    if matched_candidate:
                        abs_path = str(matched_candidate)
                        covered.setdefault(abs_path, set())
                        covered[abs_path].update(range(start_line, end_line + 1))
                except (ValueError, IndexError):
                    pass
        return CoverageData(source="go", covered_lines=covered)

    @classmethod
    def _parse_cobertura(cls, path: Path, project_root: Path) -> CoverageData:
        covered: dict[str, set[int]] = {}
        tree = _xml_parse(str(path))
        for cls_elem in tree.findall(".//class"):
            filename = cls_elem.get("filename", "")
            abs_path = str(Path(filename) if Path(filename).is_absolute()
                           else project_root / filename)
            lines: set[int] = set()
            for line_elem in cls_elem.findall(".//line"):
                try:
                    hits = int(line_elem.get("hits", "0"))
                    if hits > 0:
                        line_no = int(line_elem.get("number", "0"))
                        if line_no >= 1:
                            lines.add(line_no)
                except ValueError:
                    pass
            covered.setdefault(abs_path, set()).update(lines)
        return CoverageData(source="cobertura", covered_lines=covered)
